dist: bionic
env:
  global:
  - TARBALL_ROOT=/opt/tarballs
before_script:
- mkdir "$TARBALL_ROOT"
- wget -O '/tmp/am-toolchains.zip' 'https://github.com/RMerl/am-toolchains/archive/master.zip'
- wget -O '/tmp/asuswrt-merlin.zip' 'https://github.com/RMerl/asuswrt-merlin/archive/master.zip'
script:
- pushd /tmp
- unzip '/tmp/am-toolchains.zip'
- unzip '/tmp/asuswrt-merlin.zip'
- pushd am-toolchains-master/brcm-arm-hnd
- ls | grep crosstools | while read dir; do { tar cf - "$dir" | zstd - -o "${TARBALL_ROOT}/${dir}.tar.zst" } done
- popd
- pushd am-toolchains-master/brcm-arm-sdk
- ls | grep hndtools | while read dir; do { tar cf - "$dir" | zstd - -o "${TARBALL_ROOT}/${dir}.tar.zst" } done
- popd
- pushd asuswrt-merlin-master/tools/brcm/K26
- ls | grep hndtools | while read dir; do { tar cf - "$dir" | zstd - -o "${TARBALL_ROOT}/${dir}.tar.zst" } done
- popd
after_script: rm -rf /tmp/*

addons:
  apt:
    packages:
    - zstd
    - wget
