name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install Dependencies
      run: sudo apt install -y zstd
    - name: pack
      id: pack
      env:
        TARBALL_ROOT: /opt/tars
      run: |
        mkdir -p "$TARBALL_ROOT"
        pushd am-toolchains/brcm-arm-hnd
        ls | grep crosstools | while read dir; do 
          tar cf - "$dir" | zstd - -o "${TARBALL_ROOT}/${dir}.tar.zst"
        done
        popd
        pushd am-toolchains/brcm-arm-sdk
        ls | grep hndtools | while read dir; do
          tar cf - "$dir" | zstd - -o "${TARBALL_ROOT}/${dir}.tar.zst"
        done
        popd
        pushd asuswrt-merlin/tools/brcm/K26
        ls | grep hndtools | while read dir; do
          tar cf - "$dir" | zstd - -o "${TARBALL_ROOT}/${dir}.tar.zst"
        done
        popd
        echo ::set-output name=files::$(ls "${TARBALL_ROOT}/"*.tar.zst)
    - name: echo outputs
      run: echo -e ${{ steps.pack.outputs.files }}
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.pack.outputs.files }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
